#+title: Farsi Hymns

We are translating hymns, poems, and prayers into Persian for liturgical use.

/*Note:*/ This project uses *CC-BY-NC 4.0* with /additional stipulations/. See
the =LICENSES.d/= directory for full texts.

* How You May Use this Project

- These hymns are free to use in church services.
- You may adapt them and edit them as needed.
- You may /share/ your modified versions freely with others, provided that they
  *remain in plain text* (=.txt=) or Org-Mode (=.org=) format (as described in
  =LICENSES.d/ADDITIONAL_STIPULATIONS.org=)
- You are encouraged to submit your modifications for inclusion in this
  repository.

* What is Not Allowed

- Commercial publication or commercial distribution in any form
- Sharing of formatted or beautified editions (eg. PDF, Word, LaTeX, etc.)
- Redistributing without inclusion of the contents of the =LICENSES.d= directory.

The reason: we intend to publish these hymns in professionally typeset books. If
polished digital editions were freely available, it would undermine that goal.
The plaintext versions here are free for liturgical and collaborative use, while
rights to produce finished editions remain with the Licensor.
