** تضرعات کوچک به تئوتوکوس:
*** آغاز

_کاهن_: متبارک خدای ماست همیشه، همینک، و تا ابدالآباد.
_کر_: آمین.
_کاهن_: اِی پادِشاهِ آسِمانی و تَسَلّی‌بَخش و روحِ حَقیقَت، که حُضورَت دَر هَر جا است و انبارَندۀِ هَمِگی هَستی. بیّا و دَر دِلِ ما ساکِن باش. ما را زِدای از هَر لَکه و گُناه و ما را نِجات فَرما اِی نیکو.
_قاری_: آمین.

*** دُعایِ سه‌قُدوس

_قاری_: اِی خُدایِ قُدوس، اِی قَڤّیِ قُدوس، اِی جاڤیدِ قُدوس، به ما رحم نَمای. (سه بار)

جَلال بَر پِدَر و پِسَر و روح‌اُلقُدُس؛ هَمینَک و هَمیشه و تا ابداُلآباد. آمین.

اِی ثالَوثِ قُدوس به ما رَحم فَرمای. پَرڤَردِگار، ما را از گُناهانِ ما پاک کُن. اِی اُستاد، خَطاهایِ ما را به‌آمُرز. اِی قُدوس، بیماریِ ما را به جَلالِ نامِ تَو عِیادت و بِهبودی نمای.

خُداڤَند، رَحمَت نَمای. (سه بار)

/جلال بر…؛ همینک و… آمین./

اِی پِدَرِ ما که دَر آسِمان‌هائی، تَقدیس شَڤَد نامِ تَو! اِرادۀِ تَو چُنانکه در آسِمان بَر زَمین نیز انجام شَڤَد! نانِ روزانۀِ ما را اِمروز به ما بِدِه! و دیّونِ ما را بِبَخش چُنانکه ما نیز مَدیونانِ خَود را بَخشیده‌ایم. و ما را دَر ڤَسڤَسه مَیاڤَر بَلکه از شَریر ما را رَهائی دِه!

/کاهن/: زیرا مَلَکوت و قُدرَت و جَلال از آنِ تَوست: از آنِ پِدَر و پِسَر و روح‌اُلقُدُس؛ هَمینَک و هَمیشه و تا ابَداُلآباد.

_قاری_: آمین.

*** ۱۴۲مین مزمور

خُداڤَند رَحمَت نَمای. (۱۲ بار)

/جلال بر…؛ همینک و… آمین./

بیّا مَسیح را بِپَرَستیم، پادِشاهِ مان.
بیّا بِپَرَستیم و بِخَمیم فُروتَن پیشِ مَسیح، پادِشاه و خُدای مان.
بیّا بِپَرَستیم و دَراُفتیم فُروتَن پیشِ مَسیح، حَقیقَتاً خُدا و پادِشاهِ مان.

—(در این موقع، ۱۴۲مین مزمور خْوانده شڤد (۱۴ ۳م بنا بر شماره‌گذاری عبری))—

*** یهڤه خداست و تروپاریا

یَهڤَه خُداست و جِلڤه بَر ما رُخشید. مُتِبارِک هَمان که می‌آیَد به عُنڤانِ خُداڤَند است.

آیه‌ها:
۱. یَهُڤَه را تَمجید کُنید زیرا که نیکو است! ڤَفادار‌ی‌اش ابَدی است!
۲. هَمۀِ مِلَّت‌ها مَرا اِحاطه می‌کَردَند، با نامِ یَهُڤَه آن‌ها را با شَمشیر دَو نیم کَردم.
۳. این کارِ یَهُڤَه است، دَر نَظَرِ ما شِگِفت‌اَنگیز است.

(به لحن Ὁ ὑψωθεὶс ἐν τῷ Ϛαυρῷ)

به࣪ تِئَوتَـــوکـــوس، عـــاصیّـــان بِ࣭شِتآبیم (ذ)
مآ مَساکیـــن زاـــنـــو زَنیـــم دَر تَوبه࣪ نیز (ذ)
دَ࣪ر نِدآ زَدَ࣪ن از تَ࣪هِ جان. (ذ)
اِ࣭ی بانو࣭ کُمَـــک و شَـــفَقَ࣪ت بَراـــیِ࣭ ما نَ࣪مـــا (ذ)
چَ࣪ون تَحتِ࣭ میرَـــندِگـــی از خَ࣪طایآنِ زیّـــادیم. (ڤو)
دَ࣪ستِ خادِ࣭می خالې نَگُذآر. (ذ)
آی بی‌دِرَـــنگ چَـــون اُمېدِ تَنهـــامونی. (ڤو)

/جلال بر پدر و پسر و روح‌القدس؛/ —(تکرارش کن)—

/همینک و همیشه و تا ابدالآباد. آمین./

بانو به کِـــرداـــرهـــایِ پُـــرِ قُڤَّ࣪تَت (ذ)
هَرگِز ساکِـــت نَـــتَـــڤانیـــم؛ نالایِ࣭قیـــم. (ذ)
چَون اَ࣪گر نه ایستآدی تَو بَهرې شَفاعَـــت (ذ)
کی می‌رَهانیـــد ما راـــ زېن انبــــوهِ خَطَ࣪رهـــا؟ (ذ)
کی ما را نِگَـــه می‌داـــشت حَقاً آزآد تا به حـــال نیـــز؟ (ڤو)
اَ࣪ز تَو هیچ بَ࣪رنَگَردېم چَون مُدآم (ذ)
می‌رَهانـــی هَـــر خادِ࣭مَت از هَـــر بَلـــا (ڤو…ذ)

*** ۵۰مین مزمور

—(در این موقع ۵۰مین مزمور خْوانده شڤد. بنا بر شماره‌گذاریِ عبری، ۵۱م هست)–

*** اڤّلین ترانە
**** هیرمَوس

دَر گُذَ࣪ر از دَریـــا چَون زَمېنِ خُشک، (غ)
دَ࣪ر فَرار از مِـــصر، ڤَـــز (پا)
فَلاکـــاتِ هَمآن دیّآر، (غ)
اِسرآئیلې نِدآ زَد فَریـــاد: (ک)
نِجات‌بَ࣪خش و خُداـــ را صِدآ زَنیم (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

زِ ڤَ࣪سڤَسه‌هـــا اِحاطە شُدهٰ‌م. (غ)
به دُنبآلِ رَهایـــی، مَـــن (پا)
به پَنـــاهَت دَڤآن آیَم. (غ)
اِی مادَ࣪رِ کَلآم، دائِ࣭ماً باکِره، (ک)
از مُشکِ࣭ل و خَطَـــر رَهایې‌ام ده. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

یورِ࣭شِ هَڤَـــس می‌لَرزآنَندَم؛ (غ)
قَ࣪طعِ اُمیـــد تَــ(پا)ــمامِ
رـــوحَم‌و فِشُردهٰ‌ست. (غ)
با صُ࣪لحِ پِسَ࣪ر و خُداـــیـَــت (ک)
آرامِ࣭شَم ده، اِـــی باکِرۀِ پاک. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

ناجې را زاده‌ـــ‌ای کە هَم خُداست. (غ)
بآخْواهِ࣭شَم کَـــز پَــ(پا)ــریشانـــی
رَها بِشَڤَـم (غ)
به حِ࣭فظِ جآنَم پَنـــاه ده (ک)
فَدآیِ تَـــو کُنَم جـــانَم و دِ࣭لَم را. (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

گَ࣪رچە مَریـــض ام— بَدَ࣪ن و جان— (غ)
مادَ࣪رِ بَغِ رـــاست، مَــ(پا)ــرا
لایِــقِ لُطفَت بِدان (غ)
ڤَز رَهبَرې اِلٰهې راهنَمـــام کُن (ک)
چُنانکه نېک و حامِـــلِ نیکې هَستـی. (غ)

*** سەڤُّمین تَرانە
**** هیرمَوس

تَ࣪و مِعمآرِ گُنبَـــدِ فِلَّ࣪کی، ڤَـــ کِلیسا (غ)
مې‌شناسَد تُرآ چَو بانـــی‌اش. (ک)
دَر عِـــشقِ تَو، هَ࣪م مَرا (غ)
بَنآ کُن، اِی قُلـــۀِ ‌(ک)
هَمە࣪ اِمیال، و بُنیـــادِ (ذ)
هَ࣪مۀِ ڤَفآداران، یآخُدآ مَردُ࣪م‌عاشِ࣭ق. (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

پَنآه و سِ࣭پَرِ جـــانَم قَرار داده‌ـــ‌اَم تُرا (غ)
مَ࣪را بِرِسآن بَندَرگـــاهَت، (ک)
بـــاکِره خُ࣪دازا.ـــ (غ)
باعِ࣭ثِ هَـــر نیکـــی (ک)
هَستې، تَو اِ࣭ی تِکیەگـــاهِ (ذ)
هَ࣪مۀِ ڤَفآداران، بَـــرتَرین سِ࣭تودە. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

عُذرا زِ تَ࣪و می‌خْواهَـــم کَـــز خاشِ جـــان بِ࣭رَهان. (غ)
طوفآنِ حُ࣪زنَم‌و آرـــام کُـــن (ک)
مـــی‌طَ࣪لَبَم ازَت، (غ)
چَون دُ࣪غدِ خُداـــئی، (ک)
چِشمۀِ آ࣪شتی را زاـــدی، (ذ)
حامِـــلِ مَســـیح، اِی تَنهآ لایِ࣭قِ آ࣪فَرین. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

مُ࣪ڤهِبآتِ نیکـــیَت بَر هَمِگـــان بِ࣭بَخشای. (غ)
کِ࣭رفەگَ࣪رعَظېم و چِشمـــۀِ (ک)
هَ࣪ر نیکې‌و آڤَردی. (غ)
تَڤانآی قُدرَـــت را (ک)
دَ࣪ر زِهدآنِ تَو بُـــردی. (ذ)
قادِ ـــرِ هَر کـــاری، اِی فَـــرخُنده زِ࣭ خُدا. (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

چُنآن امرآضِ شَدیـــد ڤـَــ هَ࣪ڤَس‌هـــایِ تاریـــک (غ)
مې‌آزمایَند مَ࣪را؛ لُطفـــاً تَو (ک)
مَرآ کُمَک کُنې. (غ)
می‌شناسَمَــــت چُنیـــن: (ک)
که تَ࣪و گَنجِ࣭ بی‌پایـــانی، (ذ)
بَ࣪خشَندۀِ اېستِ گِرآن‌بَهآتَرېن شَفا. (غ)

*** ترَوپاریای اتمام

خَلـــاصِ مـــا (ک)
دِه، بَندِگآنِ مِسکـــینَت، اِی تِئَوتَـــوکوس، (ذ)
چَون گُرېزیم پَنـــاهَت، پَس از ایزَـــد، (ن)
حِمایَ࣪ت و قَلعـــۀِ ناگُـــشودَ ــــنی. (غ)

بِنِـــگرـــای (ک)
خادِ࣭مِ تُ࣪را به لُـــطف، خُدازایِ حَـــمـــید،
(ذ) هَم بَر رَ࣪نجِ دَردآمـــیزِ جِسمـــی‌ام، (ن)
شَفا ده هَم بَر تَ࣪شڤیشِ رـــوحَم. (غ)

*** گُستَردۀِ سوزان

_شماس_: اِی خُدا، مَطابِقِ ڤَفاداری‌ات بَر ما رَحم فَرمای؛ از تَو اِستِدعا می‌کُنیم، از ما بِشنَو و رَحمَت نَمای.

_کر و عڤام_: خُداڤَند رَحم نَمای. (۳ بار)

_شماس_: مُجِدَداً به خاطِرِ سَراُسقُفِ مان [اِسمَش] و اُسقُفِ مان [اِسمَش] دُعا می‌کُنیم و به خاطِرِ تَمامِ مَنصوبین و عَڤامِ مَسیح نیز دُعا می‌کُنیم.

_کر و عڤام_: خُداڤَند رَحم نَمای. (۳ بار)

_شماس_: مُجِدَداً استدعا می‌کُنیم بَرایِ رَحمَت، زِندِگی، صُلح، سَلامَتی، رَستگاری، نظارت و مراقبت، بَخشِش و آمُرزِشِ گُناهانِ خادِمانِ خُدا، هَمۀِ مَسیحیانِ مُتَّقی و راست‌کیش، ساکِنان و مِهمانانِ این شَهر و سَرزَمین، اعضا، شَوراکاران، یاڤَران، و کِرفه‌گَرانِ این کِلیسایِ مُقَدَّس.

_کر و عڤام_: خُداڤَند رَحم نَمای. (۳ بار)

_شماس_: مُجِدَداً دُعا می‌کُنیم به خاطِرِ خادِمانِ خُدا: [فِهرِست اِسم‌های‌ِ مُبتَلایان] و هَمۀِ بَرادَران و خْواهَرانِ مان دَر مَسیح.

_کر و عڤام_: خُداڤَند رَحم نَمای. (۳ بار)

_کاهن_: زیرا که خُدائی رَحیم و مُحِبّ هَستی و تُرا تَجلیل می‌کُنیم: پِدَر و پِسَر و روح‌اُلقُدُّس را؛ هَمینَک و هَمیشه و تا ابَداُلآباد.

_کر_: آمین.

*** کاثیزمای بین ترانەها

مادَ࣪رِ خُدا، دَفآعِ مُجِّـــدانـــه، (ڤو) چِشمۀِ رَحمَ࣪ت، و قَلعۀِ پاید ـــارِ ما، (ڤو) دَ࣪ر اِنتِظـــار بِمـــان، ما را رَهائی ده زِ بَلآ ڤَ زِ࣭ خَطَ࣪ر، (ذ) اِی بانو࣭ تَنهآ فِرزِ࣭ مَدَ࣪دِ ما. (ڤو)

*** چَهارُّمین تَرانە
**** هیرمَوس

مَن شَنېدَمَت، خُ࣪داڤَند، (غ)
رآجِع به اسرـــارِ طَرح‌اِ࣭لٰهیِ تَو، (ک)
مُ࣪عجِزآتَت‌و اندېشیده‌ٰم، (ذ)
ڤَ࣪ اُلو࣭هیَّـــتَت‌و سِ࣭توده‌ٰم (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

حِیرَ࣪تِ هَڤَ࣪س‌ها را، (غ)
اِ࣭ی حامِ࣭لِ سَ࣪ر و ناخُدآیِ ما، (ک)
ڤَ࣪ امڤآجِ شَرارَ࣪تَم را، (ذ)
یا خُدآعَرـــوس، آرام گَردانای. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

رَحمٰـــن را دَهر آ࣪ڤَرده‌ٰی، (غ)
نِ࣭جات‌بَخشِ هَ࣪ر سِتآیِشگَ࣪رِ تَو. (ک)
زِ࣭ ژَرفآیِ شَفَقَ࣪تِ خَود (ذ)
هَ࣪م بَر مَن بِبَـــخش، تَضَرُ࣪ع کُنَم. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

مُتنَعِ࣭مِ نِعمـــاتَت، (غ)
مې‌خْوانېم با شُـــکر تُـــرآ، اِی مُنَزَه، (ک)
چَ࣪ون خُدآمادَر می‌شنآسیمَت، (ذ)
ڤَ سِپاس گُزـــاریم زِ هِدایا. (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

ما که د ـــاریم تُرآ به عُـــنـ(غ)ـڤآنِ
تِ࣭کیه‌گــاه، ڤَ اُمېد، و دِ࣭ژِ سِـــفـ(ک)ـتِ࣭
نِجات، از هَر بَلا، نِجات (ذ)
مې‌شَڤیم، اِی بَـــرتَرین سِ࣭توده. (غ)

*** پَنجُّمین تَرانە
**** هیرمَوس

مآ را، خُداڤَ࣪ند، (ذ)
بِتابآن با فَ࣪رمانآنِ خَود. (غ)
بازوی تَو بُلَ࣪ند، بَر ما عَطـــاـ(ک)ـیِ
صُ࣪لحِ تَ࣪و فَرمای، (ذ)
تَو اِ࣭ی عاشِ࣭قِ آدَمی. (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

شادېِ ناآلوـ(ذ)ـدَ࣪ت‌و
به࣪ مَن بِ࣭ده اِ࣭ی خالِ࣭ص. (غ)
دِ࣭ل بِسآز لَبرېزِ شادې (ک)
چَ࣪ون او࣭ را بُ࣪رده‌اې: (ذ)
سَ࣪رچِشمۀِ هَ࣪ر خَوشی. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

رَستگآر بُکُن ما را (ذ)
زِ࣭ هَر خَ࣪طَرات، اِی مُ࣪نَزَه، (غ)
چَون تَ࣪و رَستگارې‌ِ جاڤېد (ک)
ڤَ صُ࣪لحِ فَ࣪راتَـر (ذ)
زِ هَ࣪ر فَهمې را آڤَردەٰی. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

تیرِگېِ گُناهـــاـ(ذ)ـنَم‌و
بِ࣭زِدآ، خُدآعَروس، (غ)
با تآبِ نافِ࣭ذِ فُرو࣭غِ خْویش. (ک)
مادَ࣪ر شُدەٰی بِدو: (ذ)
نورِ اِ࣭لٰهېِ آزَّلـی (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

ضَ࣪عفَم را دَڤآ (ذ)
کُ࣪ن— ساخته زِ دَ࣪ستِ هَ࣪ڤَس‌ها. (غ)
به تیمآرَت لایِ࣭قَم بِدآن (ک)
سَالِ࣭مَم کُن، اِی ناب، (ذ)
دَوباره با شَ࣪فاعآتِ خَود. (غ)

*** شِشُّمین تَرانە
**** هیرمَوس

لابـــه‌ام راـــ (ک)
به خُ࣪داڤَـــند مې‌ریزَم (ذ)
ڤَ࣪ به ڤِ࣭ی دِهَ࣪م بَیـــانی زِ رَـــنجَـــم. (ن)
بِبېن که پُ࣪ر از شُرو࣭ر شُده دِ ـــلَـــم (ذ)
ڤَکنو࣭ن که جآنَم نَزدیـــکِ دوزَ࣪خ شُدەٰست (غ)
چَ࣪ون یونِـــس اِ࣭ستِدعآ کُنَم (ذ)
یآ خُداـــم از فِســـاد بَرخیزآن مَرا. (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

چَون زِ مـــرگ، عُذراـــ، (ک)
ڤَ زِ࣭ فِسآد و تَ࣪باهې— (ذ)
ڤَقتې سِرِـــشتَم اســـیرِ فِســـاد بود — (ن)
ڤَز دَهآنِ مَـــوت، ذاتِ مَرا رَهـــا کَرد (ذ)
بآ دادَ࣪نِ خَود بـــه مَ࣪حدودۀِ مَوت، (غ)
ایزَ࣪د و پو࣭رَت‌و بِخْواـــه (ذ)
ک‌آزآد شَڤَـــم از هَر کـــینِ هَر دُ࣪شمَنا. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

می‌داـــنَم تُرا (ک)
حِ࣭فظِ زېستَم، و دَفـــاع، (ذ)
ڤَ࣪ سِپَـــرَش، عُذراـــ؛ جَ࣪معیّـَــتِ (ن)
ڤَسڤَسه راـــ مې‌زِدآئی ڤَ حَملـــاـ(ذ)ـتِ
لَشکَـــرِ دیڤـــی رآ دور مې‌رانی. (غ)
بې‌ڤَقفـــه اِ࣭لتمآس کُنَم: (ذ)
زِ فِسآدِ هَڤَـــس بِرَهان مَرا. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

دُختَـــر، نِجـــاـ(ک)ـتِ
کامِ࣭لِ جانِ ما، (ذ)
آرامِـــش تَ࣪وئی دَ ـــر شِ࣭کَنجـــه ڤَ (ن)
تِ࣭کیەگـــاه، دِ࣭ژِ ایستِ پَنـــاهی، (ذ)
ڤَز نو࣭رِ تَـــو تا ابَـــد ما شادی کُنیم. (غ)
اِ࣭ی بانـــو، ما را هَمینَک (ذ)
از هَڤَ࣪س و خَطَـــر رَهایې بِده. (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

بیمـــار، دِ࣭رـــاز (ک)
کِشېدَم رویِ تَ࣪ختِ خَود. (ذ)
شَفآ بَرایِ جِـــسمَم مَوجـــود نیست. (ن)
چَون او را زــــادی: خُدآ ڤَ ناجـــیِ (ذ)
کُلِ جَهـــان، رَهایـــی زِ࣭ هَر بېمارې، (غ)
اِ࣭ی نیکـــو، مَ࣪را بِ࣭شنَڤـــا: (ذ)
زِ پوسِ࣭شِ مَرَـــض بَ࣪رخیزآن مَرا. (غ)

*** دُڤُّمین ترَوپارِ اتمام

اِی بیـــگُنــــاه (ک)
که با لُغَ࣪تی کَلــــامِ جاڤیدو بُـــردی (ذ)
بی‌بَیآن اِلتِمآس کُن هَمینَـــک و دَر ا‌ِنتِها (ن)
به اِ࣭ختیّآرِ مِـــهرِ مادَ ـــری. (غ)

—(در این موقع، دعای گستردۀ سوزان دوباره اجرا شڤد)—

*** کوداکیون عادی

حِفاظَ࣪تِ ناشَ࣪رماندَنېِ مَسیـــحیّـــان (ذ)
میّانجې به خالِ࣭قِ اصلاً ناجُنبیـــدَنـــی، (ڤو)
ناله‌هـــایِـــ مایِ عاصې را مَیاَندآز کِنـــار؛ (ذ)
بِجـــا، بِ࣭نِگَر حاجآتِ مان، ڤَ دِ࣭ه کُمَ࣪کِ مان، اِی نیـــک، بَ࣪ر نِدآگَران دَـــر ایمان: (ڤو)
زـــود باش به شَفاعَ࣪ت، وـــ بـــه اِ࣭ستِدعا شِتآبـــی. (ذ)
دائِماً پاسبآنِ هَـــر (ظ) تَکریم‌گَ࣪رَت اِی خُ࣪ـدازا.ـــ (ڤو)

*** سرودەهای صعودی

از جڤانی‌ام به بعد هڤس‌های زیادی علیهِ من می‌جنگند، اما تو مدد و نجاتِ منی، ناجی.

متنفران صهیون از دستِ یهڤه قادر مطلق رسڤا خواهند شد، چون عین چمن در آتش همەشان می‌پژمرند.

/جلال بر پدر و پسر و روح‌القدس؛/

از روح‌القدس هر جان حیات می‌یابد، و با پاکسازی افراخته می‌گردد؛ از اتحادِ سگانه روشن گشته است، به یه رازِ قدسی.

/همینک و همیشه و تا ابد الآباد. آمین./

از روح‌القدس انهارِ فیض جاری اند؛ کلِ خلقت را سیراب می‌گردانند تا که حیات فرکاشته شڤد.

*** قرائت انجیل
**** پیش‌نشین

_قاری_: می‌خْواهَم نامِ تَو را دَوره به دَوره به یادها آڤَرَم.

—(اڤلین کر همان آیه را به لحن تکرار کنه. بعد، قاری این آیه را بخْواند و دڤمین کر آیۀ اصیل را به لحن تکرار کند.)—

آ. اِی دُختَر، گوش فَرا دِه، بِبین و گوش بِسپار، قَومِ خَود را فَراموش کُن، خانۀِ پِدَرَت را، و پادِشاه شیفتۀِ زیبائیِ تَو خْواهَد شُد.

—(یک بار دیگر خْوانده شڤد. این دفعه، اڤلین کر اڤلین نصف آیه را بخْواند و دڤمین کر جڤاب دهد با بقیه.)—

_کر یکم_: می‌خْواهَم نامِ تَو را دَوره
_کر دڤم_: به دَوره به یادها آڤَرَم.

**** انجیل

_شماس:_ به خُداڤَند دُعا کُنیم که ما را لایِق سازَد تا اِنجیلِ مُقَدَّس را بِشنَڤیم.

_کر و عڤام_: خُداڤَند، رَحم نَمای. (۳ بار)

_کشماس_: خِرَد. بُلَند شَڤید! اِنجیلِ مُقَدَّس را شَنَڤیم.
_کاهن_: صُلح بَر هَمۀِ شُما باد.
_کر و عڤام_: نیز بَر روحِ تو.

_شماس_: خانِش از اِنجیل است مُطابِقِ شَهادَتِ لوقایِ رَسولِ مُقَدَّس.
_کاهن_: تَڤَجُه گُزاریم.
_کر و عڤام_: جَلال بَر تَو، اِی پَرڤَردِگار؛ جَلال بَر تَو.

—(در این موقع، کاهن یا شماس انجیل را بخواند از کتاب لوقا، باب اڤل، آیه‌های ۳۹–۴۹ و ۵۶.)—

_کر و عڤام_: جَلال بَر تَو، اِی پَرڤَردِگار، جَلال بَر تَو.

*** سرودگانِ بعد از ا‌ِنجیل

/جلال بر پدر و پسر و روح‌اقدس؛/

پِدَ࣪ر، پِسَ࣪ر، و رـــوح، ثالَُــوث د‌َر یِکپارچِگی، (ڤو) رَبِ رَحمَ࣪ت، خَطـــایِ࣭ زیآدَم‌و پـــاک کُن. (ڤو)

/همینک و همیشه و تا ابد الآباد. آمین./

بِ࣭دین شَ࣪فاعـــاتِ حامِـــلِ خُدا،ـــ (ڤو) رَبِ رَحمَ࣪ت، خَطـــایِ࣭ زیآدَم‌و پـــاک کُن. (ڤو)

/(آیه) ای خدا، مطابق ڤفاداری‌ات بر من رحم فرما، مطابق فراڤانی شفقت خود خطایم را بزدا./

(به لحن ὅλην ἀποθέмενοι)
بانو࣭ نَسِ࣭پارې مَرا به پَناهگآهی اِنسآنـــی (ذ)
بَلکه بِ࣭پَذېر لابـــۀِ࣭ خادِ࣭می فُ࣪روتَـــن، اِی بانو ‌اقدَس. (ڤو)
مُشکِلـــات دَ࣪ورَم گِ࣭رِفتَ࣪ند؛ دیگَ࣪ر نَتَ࣪ڤانَ࣪م (ذ)
تیرهایِ شِ࣭یطانان‌و تَ࣪حَمُـــل بُ࣪کُنَم از هَ࣪ر سو تَــــحتِ࣭ آتَ࣪ش، ناچـــار و خَ࣪راب چُنین. (ڤو)
پَ࣪ناهگآهی نَ࣪دارَـــم ڤَ࣪ هیچ تَ࣪سلیَّـــت جُ࣪ز تَو نیز، تَو اِی (ڤو)
مَ࣪لَکَ࣪ۀِ دَ ــــهر و࣭ اُمېد و حِمایَ࣪تِ پای‌بَندآن، (ذ)
به اِلتِمـــاسَم دِقَّ࣪ت دِه، و (ذ)
انجآم ده آن که بِـــهیـــنــــه‌ست (ڤو)

هیچ‌کَ࣪س رَد نَ࣪کُن شَ࣪رمَنده، خَلڤَ࣪ت، و بې‌فایِده که می‌دَڤَند پَنآهَت، اِـــی بآکِره خُد ـــازـــا، (ڤو)
بَلکه اِلتِمآس کُنَ࣪د و هَدیّهٰ‌ت‌و می‌گیرَ࣪د (ذ)
به انجـــامِ࣭ دَرخْواـــستِ‌ـــ خْویـــش. (ڤو)

دِگرسازې بَهرې رنجبَـــران (غ)
ڤَ تَسکین بَهرې بیمـــاران ڤاقعاً هَستی، اِی بآکِره خُد ـــازا (ن)
شَ࣪هر و قَ࣪ومَت‌ دِ࣭ه نِجـــات (ذ)
اِ࣭ی سَلآمِ دَ࣪ر مُحآصِرـــان و (ذ)
آرامِ࣭ش بَر دَ࣪رگیرآنِ طوفـــان نیز (ڤو)
ڤَ تَنها حافِظِ࣭ ایمان‌داران (ذ)

*** شفاعت کبیر

_شماس_: ای خدا، قوم خود را نجات فرمای و میراث خود را برکت نمای. بر دنیای خود با رحمت و شفقت بنگر. مسیحیان راست‌کیش را در جلال براَفراز و گنجینۀ رحمت‌های فراڤانِ ترا بر ما به‌افشان، به ڤاسطۀ شفاعاتِ بانوی پاکیزۀ مطلقِ مان: تئوتوکوس، مریمِ دائماً باکره، با قدرت صلیبِ حیات‌بخش و گرانبها، پاسبانیِ قدرت‌های بزرگڤارِ ناجسمیِ آسمانی، با استدعاهای پیش‌رو و نبیِ بزرگڤار مجلل: یحیای تعمید دهنده، همراهِ همۀ رسولانِ مجلل و قابلِ ستایش، پدرانِ مان در میانِ قدیسان و کاهن‌سرڤران و اموزگارانِ کیهانی: ڤاسیلِ کبیر، و سرمطرانان قُسطَنطَنیه: گریگوری عالمِ الهیات، و یوحنای طلادهان؛ سرمطرانان اسکندریه: آثاناسیوس، کِریل، و یوحنای رحیم؛ شگفت‌سازان: نیکولائوسِ اسقفِ شهرِ میرا، اسپِرِیدونِ اسقف شهرِ ترمیثوس، و نکتاریوسِ اسقفِ شهرِ پنطوپولیس؛ شهیدان: گِوارگئوسِ پیروز، دمیتریِ مُرّتَراڤ، ثئودورِ نَوسرباز، ثئودورِ فرمانده، و میناسِ شگفت‌ساز؛ کاهنانِ شهید: حرالابوس و الفثریوس؛ اِفّیمیای شهیدِ پر شکوه و فراشایستۀ تمجید، و بقیۀ شهیدزنان مقدس و مجلل: ثکلا، ڤارڤارا، آناستاسیا، اکاترینا، کِریاکی، فْواتینی، مارینا، پاراسکڤی، و ایرینی، و جمع شهیدانِ مقدسِ مجللِ پیروز، و جمعِ پدرانِ خدابرِ مان؛ نیاکانِ ایزدیِ دادگر: یوئاقیم و آنّا، و قدیس [اسمش] که امروز خاطرۀ او را جشن می‌گیریم، و همۀ مقدسانِ تو. ترا التماس می‌کنیم ای خداڤندِ یگانۀ رحیم، که مای گناه‌کاران را بشنڤی که به تو دعا کنیم و که بر ما رحمت فرمائی.

_کر و عڤام_: خُداڤَند، رَحم نَمای. (۱۲ بار)

_کاهن_: از رحمت و شفقت و محبت برای انسانیتِ پسرِ یگانۀ تو که با او و با روحِ قدوسِ مطلق و نیک و حیات‌بخش متبارکی، همینک و همیشه و تا ابدالآباد.

_کر و عڤام_: آمین.

*** هَفتُّمین تَرانە
**** هیرمَوس

سه جَڤآنِ یَهو࣭دیّه، (غ)
به ایمآن به ثالَ࣪وث قُدوـــس رِ࣭سیده، (غ)
بآری دَر بآبِـــل (ذ)
شُعلەهآیِ کورـــه را پایمآل کُنان سُ࣪رودَند: (غ)
اِ࣭ی خُدآیِ پِدَرآنِ مـــا، یَ࣪هُڤَ࣪ه مُتِ࣭بارِـــکی! (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

مُشتاقِ رَستگارې‌مون، (غ)
اِ࣭ی ناجې، نِجـــاتِ ماها را نِ࣭هادی (غ)
دَر زِهدآنِ باکِره࣪، چَون (ذ)
حافِ࣭ظِ جَهـــان نَمودەٰـــیٰ‌ش، تَو ساکِ࣭نِ دَهر. (غ)
اِ࣭ی خُدآیِ پِدَرآنِ مـــا، یَ࣪هُڤَ࣪ه مُتِ࣭بارِـــکی! (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

از پِسَ࣪رِ تَو بِ࣭خْواه، (غ)
کامجو࣭، اِی مادَ ـــر، که رَحمَ࣪ت دِهَ࣪د به ما، (غ)
تا از عِیب آزآد شَڤـــیم (ذ)
ڤَز نِ࣭جاسَ࣪تِ رـــوح، که نِداـــ زَنیم بآ ایمان: (غ)
اِ࣭ی خُدآیِ پِدَرآنِ مـــا، یَ࣪هُڤَ࣪ه مُتِ࣭بارِـــکی! (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

ڤالِدەٰت‌و نَمودی: (غ)
بُ࣪رج‌ِ ایمِنـــی، ڤَ چِشمۀِ لافِساد، (غ)
گَنجینۀِٛ نِجآت، وـــ (ذ)
دَرڤازۀِ تَوبه بَرآیِ هَ࣪مه که سِ࣭تایَند: (غ)
اِ࣭ی خُدآیِ پِدَرآنِ مـــا، یَ࣪هُڤَ࣪ه مُتِ࣭بارِـــکی! (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

ناخَوشېِ بَدَ࣪ن وـــ (غ)
بیمارېِ جـــان را، اِی تَ࣪و خُدآمادَ࣪ر، (غ)
شَفآ ده بَ࣪هرِ ماهـــا (ذ)
عُشآق که آییـــم به پَنـــاه اِلٰهېِ تَو. (غ)
برآیِ ما، مَســـیح و ناجــــی را زادەـــ‌ای. (غ)

*** هَشتُّمین تَرانە
**** هیرمَوس

پادِشـــاهِـــ (ک)
آسِمآن را بِ࣭سُرای، (ذ)
با سِ࣭پاهـــانِ سِپِ࣭هرِ بی‌شُمـــار، ڤَـــ (ن)
بېکران دَر هَـــر زَمانه او را ڤالـــا کُن. (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

بانو، نَدیـــده مَگـــیر (ک)
خادِمآنِ گِدآت‌و (ذ)
که با شَرَـــف و شاد ـــی می‌سُرـــایَند (ن)
ڤَ تُ࣪را، اِی دُختَـــر، هَ࣪ر دَورآنی می‌سِتـــایَند. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

می‌‌بَـــخشی (ک)
شَفاهایِ فَ࣪راڤان، (ذ)
اِی باکره࣪، بَرآیِ هَـــر خْوآنَندەٰـــت کـــه (ن)
زادَ࣪نَت‌و سِتـــایَد که فَ࣪را زِ࣭ گُفتـــاره. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

اِی لَبریـــزِ فِیض (ک)
هَر مَرَ࣪ض و ضَ࣪عفِ جان (ذ)
ڤَ رَ࣪نجِ تَـــن را شَفـــا می‌بارـــانی، (ن)
تا سِ࣭تایِشِ فَـــرِّ تُرآ نِگَ࣪ه بِد ـــاریم. (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

تاختِ هَڤَـــس‌ها ڤَ (ک)
حَمَلآتِ اِغڤـــا را (ذ)
عُذرا، خُنثٰـــی ڤَ زِ مـــا دور می‌رـــانی، (ن)
ایدو࣭ن تا هَر دَورـــه سِتایِ࣭شگَرانِ تَـــو ایم. (غ)

*** نُهُّمین تَرانە
**** هیرمَوس

نِجـــات‌یاب از طَرېقَت، (غ)
اِی باکِره، اقرـــارَت (ک)
کُنیم که دَ࣪ر حَقیقَـــت تِئَوتَ࣪وکوسی (غ)
با جَ࣪معِ کُ࣪رِ افلـــاک، مـــا بُزُ࣪رگَت مې‌داریم. (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

رَدّ نَـــکُن رو࣭دِ اَ࣪شکَم (غ)
چَ࣪ون تَو دَر زِهد ـــانَت (ک)
او را بُردەٰـــی که هَر اـــشکِ هَر قېافه (غ)
را زُدوده࣪ چون مَســـیح است: ایزَ࣪د آدَ࣪م‌زاده. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

اِی بـــاکِره دِلَ࣪م‌و (غ)
پُ࣪ر کُن از مُژد ـــه، چَون (ک)
شادېِ هَ࣪مه دَریـــافت کَ࣪ردی تو࣭ زِهدآن، (غ)
ڤَ هَ࣪ر اندو࣭هِ گُنـــاه رـــا تَو بُ࣪ردەاې زِ بِین. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

عُذرـــا، بَندَ࣪ر و پَ࣪نـــاه (غ)
ڤَ دِ࣭ژِ سِفت بَرـــایِ (ک)
آنان باش که࣪ به سایـــە ات فَرار کُنَ࣪ند، (غ)
ڤَ اِحاطەٰ࣪شان خُداـــزـــا تَو حِ࣭فاظَ࣪ت شَڤی. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

پَرتَـــوهایِ࣭ فُرو࣭غَت (غ)
دِ࣭ه، اِی دوشیزـــه، تـــا (ک)
ما را رَوشَ࣪ن از ظُلمَـــتِ غِفلَ࣪ت کُنی (غ)
که پارسانه اِعِلام کُنـــیم تُرآ، یَاخُ࣪دازا. (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

دَر مَـــنطِقۀِ بَ࣪لا، (غ)
نِزآر، زِ کار اُفتـــادَم، (ک)
ڤَ شُدم خْواـــر، یَاعُذرـــا، بِدونِ࣭ قُڤَّ࣪ت؛ (غ)
مَرَ࣪ضِ مَ࣪را دَڤـــا ڤَـــ تَبدېل کُن به قُدرَ࣪ت. (غ)

**** عظیم‌نمایی‌ها
***** عادیِ تضرعات

/فَ࣪رخُنده گُفتَ࣪نَت شایِستـــهٰ‌ست (ذ) به࣪ راستې، ڤالِ࣭دۀِ خُ࣪داـــمون، (ذ) دآئِماً سَعېد، هَڤاره مُ࣪بارَـــک، تِئَوتَ࣪وکوس، جُمله بې‌گُناه. (غ)/

اَ࣪ز کِروبیّـــان شَ࣪ریف‌تَ࣪ر توئې (غ)
ڤَ࣪ز سِرافیــــان تَـــو بی‌نَظـــیر بآشُکو࣭ه‌تَرې (غ)
کَلَمَت‌اُللّٰه‌ راــــ زادې بِدو࣭نِ فِ࣭ســـاد؛ (غ)
ڤاقعاً توئې خُداـــزاـــ؛ بُـــزُ࣪رگَت مې‌داریم. (غ)

بآلا زِ࣭ افلـــاک توئی، ڤَ پاک‌تَ࣪ر (غ)
از نورِ آفتـــآب، اِـــی تَ࣪و بانـــویِ کُلِ࣭ جَهان، (غ)
مآ را رَ࣪هاندې زــِـ نِفرېنِ نیّاکآنـــی (غ)
پَس سُ࣪رایآن تَجلیـــلَـــت گُـــزاریم بآ شَرَـــف. (غ)

آه زیرآ انبـــوهِ گُناهِ مَن (غ)
جِ࣭سمِ مَن مَریـــض است، رو࣭حَم نیـــز هَ࣪مچُنین بیمآر (غ)
دَ࣪ر لابه خْواندَ࣪نَـــت، مَن مې‌دَڤَم پَنآهَـــت، (غ)
اِی تَ࣪و لَبرېزِ فِیـــض و اُمیـــدِ بی‌چآرِگـــان. (غ)

اَ࣪ز خادِ࣭می نـــاشایِسته قَبـــول (غ)
بُ࣪کُن لابه‌هـــا را به شَ࣪فاعَـــت به خاطِ࣭رِ ما (غ)
بآ او که آڤَ࣪رد ـــی، اِی ڤآلِدۀِ مُ࣪نجـــی (غ)
بَرآمون شَو شفـــیعِ، اِ࣭ی بانـــویِ جُمله࣪‌ جَهان. (غ)

مآ این تَرانـــه را مُشتآقانه (غ)
شآد به تَو، خُداـــزاـــ، مې‌سُراـــئیم. ایدو࣭ن با هَم (غ)
بآ یَحیآیِ پېش‌رَوـــ ڤَ جَ࣪معِ مُقَدَّ࣪ساـــن (غ)
دُعآ کُن، تِئَوتَـــوکـــوس، بر مـــا شَفَقَ࣪ت آیَ࣪د. (غ)

لآل شُده لبـــانِ࣭ بی تَ࣪قڤایآن (غ)
که࣪ حُرمَ࣪ت‌و رَـــد کَـــرد به نِگـــارِ ڤالایِ تان (غ)
که࣪ مَوسو࣭م به نِ࣭شان‌دِ࣭هِ حَ࣪قیقین رآه است (غ)
تَ࣪ڤَسُطِ لـــوقا قِدیـــس و اِنجېل‌نِڤېس. (غ)

***** TODO اضافه برای عیاد

—(در این موقع سرودگان بزرگنمای دیگر خْوانده شڤند: برای عید معبد محلی و اگر روز کنونی یه جشن کبیر باشد، بزرگنمای آن نیز خْوانده شڤد)—

***** آخرین عادیِ تضرعات

جَ࣪معِ سِ࣭پاهـــانِ آسِ࣭مانې، (غ)
پېشر‌َڤِ࣭ ڤالـــایِ‌ـــ رَ࣪ب، و رَسولان دَڤازدَه‌ـــ، (غ)
ڤَ࣪ جمله قدېســـان، پِیڤَ࣪ند با تِئوتَو࣭کوس: (غ)
دُعآ ڤَ شَفاعَـــت دِه بَراــــیِ نِجآتِ ما. (غ)

*** دعای سه‌قدوس

—(دعای سه‌قدوس دوباره برخْوانده شڤد.)—

*** اپولیتیکیای پشیمانی

رَحمَت ده به ما اِی خُداڤَند، رَحمَت ده به ما، زیرا از هَرگونۀ دَفآعی ما عاجِریم. مایِ گُناه‌کاران این اِلتِماس را به دَستِ تَو می‌آڤَریم اِی سَرڤَرِ مان رَحمَت ده به ما.

/جلال بر پدر و پسر و روح‌القدس؛/

اِی خُداڤَند رَحمَت دِه به ما چَون هَر اِعتِماد را سِپُرده‌ایم به تَو. بَر ما کُلِ خَشمِ خَود را نَریزان و خَطاهای زیادِ مان را به یاد نَسِپار، بَلکه الان هَمچَون رَحمٰن، ما را بِنِگَر و ما را از دُشمَنانِ مان بِرَهان، چَون خُدایِ مانی و قَومِ تُوئیم؛ هَمۀِ ما کارِ دَستِ خَودِ تَوئیم و حالا بَر اِسمِ تَو نِدا زَده‌ایم.

/همینک و همیشه و تا ابدالآباد. آمین./

دَرڤازه‌هایِ شَفَقَت را بُگشای به ما اِی اقدَس و خُدازا، با هَر اُمیدِ مان سِپُرده به تَو، ناکام نَمانیم. به ڤاسِطۀ تَو بِرَهیم از هَر بَلا، چَون رَستگاری هَستی بَر نِژادِ مَسیحی.

*** گستردۀ سوزان افزوده

—(مجدداً گستردۀ سوزان برخْوانده شڤد ولی این دفعه، تضرعات اضافه هم برخْوانده شڤند بعد از خْواندن فهرست نام‌ها و پیش از مهر کاهن:)—

_شماس_: مُجِدَداً دُعا می‌کُنیم بَرای حِفاظَتِ این کِلیسای مُقَدَّس و این شَهر و هَر شَهر و هَر دِه، و رَهانیدَنِ شان از مَرَض، طاعون، گُرُسنِگی، ڤَز هَر زِلزِله، سِیل، آتَش، شَمشیر، ڤَز یورِشِ دُشمَنان، جَنگ داخِلی، ڤَز گَشتِگیِ غِیرِ مُنتَظِره. و بَرای رَحمَتِ هو که مُحِبِ هَمۀ افراد هست، که بَخشَنده و مِهرِبان باشَد و چَو خُدای نیکِ مان دِقَّت دِهَد به ما، ڤَ بَرای این که هَر خَشم و مَرَض را که بَرعَکسِ ما کار می‌کُنَد از ما هو به‌افشانَد و دور بِرانَد، و ما را از داڤَریِ آیَندۀ دادڤَرِ خَود که زود می‌آیَد نِجات دِهَد، و رَحمَت دِهَد به ما.

_کر و عڤام_: خداڤند رحم نمای. (۳ بار)

_شماس_: مجِدَداً دُعا می‌کُنیم که خُدای خُداڤَند صِداهای لابه‌های مای گُناهکاران را بِشنَڤَد و رَحمَت فرمایَد بَر ما.

_کر و عڤام_: خداڤند رحم نمای. (۳ بار)

_شماس_: ما را بِشنَڤای، یاخُدای ناجیِ مان، اُمیدِ هَر دَڤائِرِ زَمین و بَرای آنانی که دور بَر دَریا هَستَند، و بَر ما شَفَقَت نَمای، اِی اُستادِ ما، و نیز بَر گُناهانِ فَراڤانِ مان، و بَر ما رَحمَت فَرمای.

_کر و عڤام_: خداڤند، رحم نمای. (۳ بار)

_کاهن_: زیرا که تَو یه خُدای رَحیم هَستی، و تُرا تَجلیل می‌کُنیم، پِدَر و پِسَر و روح‌اُلقُدُّس را، هَمینَک و هَمیشه و تا ابَداُلآباد.

_کر و عڤام_: آمین.

*** برکت مرخصی

_کاهن_: مَسیح که هَست که خُدای ڤاقعیِ مان است، به شَفاعاتِ مادَرِ پاکِ مُطلَق و جُمله بیگُناهِ خْویش، ڤَز قُدرتِ صَلیبِ عَزیز و حَیات‌بَخش، حِفاظَتِ قُدرت‌های بی‌جِسمیِ گِرامیِ آسِمانی، اِلتِماس‌های نبیِ شَریف و باشُکوه یَحیای پیش‌رَڤِ تَعمید دَهَنده، و رَسولانِ مُقَدَّس و مُجَلَّل و سِتودَنی، شَهیدانِ پیروز، و پِدرانِ عادِلِ خُدابَر، نیاکانِ گِرامیِ مَسیح، یَؤاقیم و آنّا، و هَمۀ مُقَدَّسان، رَحمَت فَرمایَد بَر ما و نِجات دِهَد، چَون نیکو و عاشِقِ آدَمیَّت هَست.

*** ثئوتوکیای مرخصی و نیایش

(به لحن Ὅτε ἐκ τꙋ͂ ξύλꙋ)

دَ ـــستَـــت نیرومَ࣪ند، تَو حِ࣭فاظَ࣪ت (پا)
بَ࣪ر پَناه‌دَڤآنِ مَؤمِـــنَـــت می‌بَـــخشی، نیکو࣭. (غ)
مآیِ عآصیّان شَفېعی جُ࣪زِ تَـــو نَ࣪داریم (پا)
که࣪ دُعـــا بی‌ڤَقفه࣪ کُنَـــی (ن)
به حُضو࣭رِ خُدآ بَـــرآمون تَ࣪قصیرآت‌بَران دَر هَ࣪ر مَرَـــض و خَطَـــر. (پا)
پَـــس مـــی‌خَ࣪میم فُ࣪روتَن پېشَـــت (غ)
اِ࣭ی مادَ࣪رِ بَ࣪غِ بَریـــن گـــاه (ذ)
خآدِم‌هآت‌و بِ࣭رَهآن از فَ࣪لاکـــات. (پا)

بـــه اَـــندو࣭هگینآن تَوئې شادی (پا)
ڤَ࣪ به مَظلومآن حِفاظَـــت، بـــه گُرُ࣪سنِگآن غَذا، (غ)
به࣪ کورآن عَصآ، به غَ࣪ریبـــان تَ࣪سلیَّ࣪ت (پا)
عِ࣭یادَ ـــت بَ࣪هرِ مَ࣪ساکیـــن (ن)
ڤَ به مُ࣪بتَلایآن، آـــشتې و سآیِبآنی، ڤَ࣪ به یَتیمـــان یاڤَری. (پا)
مـــادَ ـــرِ࣭ خُدآیِ بَرېن گاه، (غ)
بِ࣭شِتاب اِی پآک، به لابـــه‌مون: (ذ)
بِ࣭رَهآن خِدمَ࣪ت‌کارآنَت از گُناه (پا)

—(بعد، دو ثئوتوکیای دیگر. اڤلش در قصمت مخالف چهارمین آڤاز در هشتآڤازنامه پیداست ڤلی رسمی است که در این موقع هردو بنظر دڤمین آڤاز خْوانده شڤند.)—

بِـــپَذیر اِ࣭ی بانـــو دُعاهـــا زِ࣭ خُدّآمَت و (پا)
رَهآ بُکُ࣪ن ما را (ذ) از نیّآز، تَشڤېش، و هَ࣪ر اندوه. (پا)

سِپُـــردَم به پېشِ تَـــو هَ࣪ر اُمیـــدَم، خُدآمادَر. (پا)
لُطفاً مَرا نِگـــه‌داـــ(ذ)ـرې در بَندَرگآهِ تَو. (پا)

*** پایان

_کاهن_: با شَفاعاتِ پِدَران و مادَرانِ مُقَدَّسِ مان، اِی خُداڤَند یَسوعِ مَسیح، بَر ما رَحمَت و نِجات فَرما.

_کر و عڤام_: آمین.

*** Attributions

Everything in this document, unless noted otherwise, was translated by me, Anastazius, Khayatidaryan.

The verses at یهڤه خداست we're taken directly from the ecumenical translation of the holy scriptures «ترجمۀ بین الکلیسائی» also known as «ترجمۀ ترسایان».

The verse before each of the troparia of the canon was suggested by our brother Petros (Kyan). Prior to his suggestion, what I had was «قدسی‌ترین تئوتوکوس، ما را نجات بده.»

Early on in the process, there was an anonymous user in telegram who gave me a lot of feedback on odes I and III. Unfortunately, I cannot identify this person, and he has deleted his account, and later, I lost access to my account.

*** A Note About the Tetragramaton

You'll notice that in various places we translated what in Greek is «Κύριος» ( “Lord”) into Persian as the tetragramaton itself, rather than the equivalent, خداڤند or similar. This is to align with the aforementioned ecumenical translation which favours the use of the tetragrammaton over its euphemism. This may be seen as a questionable choice as the Septuagint favors the euphemism over the actual tetragrammaton, and therefore some may decry it as an unorthodox decision. From my perspective, the ecumenical translation is the closest thing that we have to an Orthodox translation of the scriptures in the Persian language, so I would rather align with it than to not do so. For anyone who disagrees, the word can be substituted easily with خداڤند as needed, as they are both trisyllabic.

*** A Note About Orthography

You will also notice that my spelling of certain words is a little bit non-standard. For example, I used the archaic Persian letter, veh ڤ, as a substitute for waw و in some places. This is because we have a great need for precision in the translation of metrical texts. And the current Persian orthography harkens back to a time when rather than a solid V sound, the Persian language was pronounced with a bilabial fricative. Now, the phonetics have diverged, and in the modern orthography, the one و letter is overloaded with at least four different pronunciations:
- دو (ō)
- دعوا (v)
- لوله (ū)
- خواهش (silent or w)

And sometimes, the same word with the same spelling can be pronounced in multiple ways with different syllabic contents. This is fine, but within this domain we have a greater need for precision, so we've brought back the old persian letter ڤ so that و is slightly less overloaded.

Now, ـَو can unambiguously make the ō phoneme, and ـو/ـُو can unambiguously make the ū phoneme, while ـْو can make the silent phoneme.

Without this ـَو might have been “av,” ـُو might have been “ov,” etc. and there is no standard diacritical method to distinguish between these sounds. With the return of this old letter, however, the diacritics become sufficient to describe the phonemes with adequate specificity.

Next, you will notice sometimes we doubled the diacritics or used the nasalized forms of the diacritics. This can be thought of generally as an indication of accentuation. However, within metrical hymnography, its purpose is more precisely to indicate downbeats and melodic high points.

You will also notice that certain syllables are elongated with the کــــــــــــشیده symbol. This can generally be thought of as an indication of elongated phonemic vowel length. However, more precisely in the context of metrical hymnography, it is being used to indicate when a syllable is held for longer than one beat.

