** تضرعات کوچک به تئوتوکوس:
*** آغاز

_کاهن_: متبارک خدای ماست همیشه، همینک، و تا ابدالآباد.
_کر_: آمین.
_کاهن_: اِی پادِشاهِ آسِمانی و تَسلیَّت آڤَر و روحِ حَقیقَت، که حُضورَت دَر هَر جا است و انبارَندۀِ هَمِگی هَستی. بیّا و دَر دِلِ ما ساکِن باش. ما را زِدای از هَر لَکه و گُناه و ما را نِجات فَرما اِی نیکو.
_قاری_: آمین.

*** دُعایِ سه‌قُدوس

_قاری_: اِی خُدایِ قُدوس، اِی قَڤّیِ قُدوس، اِی جاڤیدِ قُدوس، به ما رحم نَمای. (سه بار)

جَلال بَر پِدَر و پِسَر و روح‌اُلقُدُس؛ هَمینَک و هَمیشه و تا ابداُلآباد. آمین.

اِی ثالَوثِ قُدوس به ما رَحم فَرمای. پَرڤَردِگار، ما را از گُناهانِ ما پاک کُن. اِی اُستاد، خَطاهایِ ما را به‌آمُرز. اِی قُدوس، بیماریِ ما را به جَلالِ نامِ تَو عِیادت و بِهبودی نمای.

خُداڤَند، رَحمَت نَمای. (سه بار)

/جلال بر…؛ همینک و… آمین./

اِی پِدَرِ ما که دَر آسِمان‌هائی، تَقدیس شَڤَد نامِ تَو! اِرادۀِ تَو چُنانکه در آسِمان بَر زَمین نیز انجام شَڤَد! نانِ روزانۀِ ما را اِمروز به ما بِدِه! و دیّونِ ما را بِبَخش چُنانکه ما نیز مَدیونانِ خَود را بَخشیده‌ایم. و ما را دَر ڤَسڤَسه مَیاڤَر بَلکه از شَریر ما را رَهائی دِه!

/کاهن/: زیرا مَلَکوت و قُدرَت و جَلال از آنِ تَوست: از آنِ پِدَر و پِسَر و روح‌اُلقُدُس؛ هَمینَک و هَمیشه و تا ابَداُلآباد.

_قاری_: آمین.

*** ۱۴۲مین مزمور

خُداڤَند رَحمَت نَمای. (۱۲ بار)

/جلال بر…؛ همینک و… آمین./

بیّا مَسیح را بِپَرَستیم، پادِشاهِ مان.
بیّا بِپَرَستیم و بِخَمیم فُروتَن پیشِ مَسیح، پادِشاه و خُدای مان.
بیّا بِپَرَستیم و دَراُفتیم فُروتَن پیشِ مَسیح، حَقیقَتاً خُدا و پادِشاهِ مان.

—(در این موقع، ۱۴۲مین مزمور خْوانده شڤد (۱۴ ۳م بنا بر شماره‌گذاری عبری))—

*** یهڤه خداست و تروپاریا

یَهڤَه خُداست و جِلڤه بَر ما رُخشید. مُتِبارِک هَمان که می‌آیَد به عُنڤانِ خُداڤَند است.

آیه‌ها:
۱. یَهُڤَه را تَمجید کُنید زیرا که نیکو است! ڤَفادار‌ی‌اش ابَدی است!
۲. هَمۀِ مِلَّت‌ها مَرا اِحاطه می‌کَردَند، با نامِ یَهُڤَه آن‌ها را با شَمشیر دَو نیم کَردم.
۳. این کارِ یَهُڤَه است، دَر نَظَرِ ما شِگِفت‌اَنگیز است.

(به لحن Ὁ ὑψωθεὶс ἐν τῷ Ϛαυρῷ)

بهٛ تِئَوتَـــوکـــوس، عـــاصیّـــان بٍشِتاٛبیم (ذ)
ماٛ مَساکیـــن زاـــنـــو زَنیـــم دَر تَوبهٛ نیز (ذ)
دًر نِداٛ زَدًن از تًهِ جان. (ذ)
اٍی بانۉ کُمَـــک و شَـــفَقًت بَراـــیٍ ما نًمـــا (ذ)
چًون تَحتٍ میرَـــندِگـــی از خًطایاٛنِ زیّـــادیم. (ڤو)
دًستِ خادٍمی خالؽ نَگُذاٛر. (ذ)
آی بی‌دِرَـــنگ چَـــون اُمؽدِ تَنهـــامونی. (ڤو)

/جلال بر پدر و پسر و روح‌القدس؛/ —(تکرارش کن)—

/همینک و همیشه و تا ابدالآباد. آمین./

بانو به کِـــرداـــرهـــایِ پُـــرِ قُڤًّتَت (ذ)
هَرگِز ساکِـــت نَـــتَـــڤانیـــم؛ نالایٍقیـــم. (ذ)
چَون اًگر نه ایستاٛدی تَو بَهرؽ شَفاعَـــت (ذ)
کی می‌رَهانیـــد ما راـــ زؽن انبــــوهِ خطًرهـــا؟ (ذ)
کی ما را نِگَـــه می‌داـــشت حَقاً آزاٛد تا به حـــال نیـــز؟ (ڤو)
اًز تَو هیچ بًرنَگَردؽم چَون مُداٛم (ذ)
می‌رَهانـــی هَـــر خادٍمَت از هَـــر بَلـــا (ڤو…ذ)

*** ۵۰مین مزمور

—(در این موقع ۵۰مین مزمور خْوانده شڤد. بنا بر شماره‌گذاریِ عبری، ۵۱م هست)–

*** اڤّلین ترانە
**** هیرمَوس

دَر گُذًر از دَریـــا چَون زَمؽنِ خُشک، (غ)
دًر فَرار از مِـــصر، ڤَـــز (پا)
فَلاکـــاتِ هَماٛن دیّاٛر، (غ)
اِسراٛئیلؽ نِداٛ زَد فَریـــاد: (ک)
نِجات‌بًخش و خُداـــ را صِداٛ زَنیم (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

زِ ڤًسڤَسه‌هـــا اِحاطە شُدهٰ‌م. (غ)
به دُنباٛلِ رَهایـــی، مَـــن (پا)
به پَنـــاهَت دَڤاٛن آیَم. (غ)
اِی مادًرِ کَلاٛم، دائٍماً باکِره، (ک)
از مُشکٍل و خَطَـــر رَهایؽ‌ام ده. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

یورٍشِ هَڤَـــس می‌لَرزاٛنَندَم؛ (غ)
قًطعِ اُمیـــد تَــ(پا)ــمامِ
رـــوحَم‌و فِشُردهٰ‌ست. (غ)
با آرامٍشِ پِسًر و خُداـــیـَــت (ک)
آرامٍشَم ده، اِـــی باکِرۀِ پاک. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

ناجؽ را زاده‌ـــ‌ای کە هَم خُداست. (غ)
باٛخْواهٍشَم کَـــز پَــ(پا)ــریشانـــی
رَها بِشَڤَـم (غ)
به حٍفظِ جاٛنَم پَنـــاه ده (ک)
فَداٛیِ تَـــو کُنَم جـــانَم و دٍلَم را. (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

گًرچە مَریـــض ام— بَدًن و جان— (غ)
مادًرِ بَغِ رـــاست، مَــ(پا)ــرا
لایِــقِ لُطفَت بِدان (غ)
ڤَز رَهبَرؽ اِلٰهؽ راهنَمـــام کُن (ک)
چُنانکه نؽک و حامِـــلِ نیکؽ هَستـی. (غ)

*** سەڤُّمین تَرانە
**** هیرمَوس

تًو مِعماٛرِ گُنبَـــدِ فِلًّکی، ڤَـــ کِلیسا (غ)
مؽ‌شناسَد تُراٛ چَو بانـــی‌اش. (ک)
دَر عِـــشقِ تَو، هًم مَرا (غ)
بَناٛ کُن، اِی قُلـــۀِ ‌(ک)
هَمەٛ اِمیال، و بُنیـــادِ (ذ)
هًمۀِ ڤَفاٛداران، یاٛخُداٛ مَردٌم‌عاشٍق. (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

پَناٛه و سٍپَرِ جـــانَم قَرار داده‌ـــ‌اَم تُرا (غ)
مًرا بِرِساٛن بَندَرگـــاهَت، (ک)
بـــاکِره خٌدازا.ـــ (غ)
باعٍثِ هَـــر نیکـــی (ک)
هَستؽ، تَو اٍی تِکیەگـــاهِ (ذ)
هًمۀِ ڤَفاٛداران، بَـــرتَرین سٍتودە. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

عُذرا زِ تًو می‌خْواهَـــم کَـــز خاشِ جـــان بٍرَهان. (غ)
طوفاٛنِ حٌزنَم‌و آرـــام کُـــن (ک)
مـــی‌طًلَبَم ازَت، (غ)
چَون دٌغدِ خُداـــئی، (ک)
چِشمۀِ آٛشتی را زاـــدی، (ذ)
حامِـــلِ مَســـیح، اِی تَنهاٛ لایٍقِ آٛفَرین. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

مٌڤهِباٛتِ نیکـــیَت بَر هَمِگـــان بٍبَخشای. (غ)
کٍرفەگًرعَظؽم و چِشمـــۀِ (ک)
هًر نیکؽ‌و آڤَردی. (غ)
تَڤاناٛی قُدرَـــت را (ک)
دًر زِهداٛنِ تَو بُـــردی. (ذ)
قادِ ـــرِ هَر کـــاری، اِی فَـــرخُنده زٍ خُدا. (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

چُناٛن امراٛضِ شَدیـــد ڤـَــ هًڤَس‌هـــایِ تاریـــک (غ)
مؽ‌آزمایَند مًرا؛ لُطفـــاً تَو (ک)
مَراٛ کُمَک کُنؽ. (غ)
می‌شناسَمَــــت چُنیـــن: (ک)
که تًو گَنجٍ بی‌پایـــانی، (ذ)
بًخشَندۀِ اؽستِ گِراٛن‌بَهاٛتَرؽن شَفا. (غ)

*** ترَوپاریای اتمام

خَلـــاصِ مـــا (ک)
دِه، بَندِگاٛنِ مِسکـــینَت، اِی تِئَوتَـــوکوس، (ذ)
چَون گُرؽزیم پَنـــاهَت، پَس از ایزَـــد، (ن)
حِمایًت و قَلعـــۀِ ناگُـــشودَ ــــنی. (غ)

بِنِـــگرـــای (ک)
خادٍمِ تٌرا به لُـــطف، خُدازایِ حَـــمـــید،
(ذ) هَم بَر رًنجِ دَردآمـــیزِ جِسمـــی‌ام، (ن)
شَفا ده هَم بَر تًشڤیشِ رـــوحَم. (غ)

*** گُستَردۀِ سوزان

_شماس_: اِی خُدا، مَطابِقِ ڤَفاداری‌ات بَر ما رَحم فَرمای؛ از تَو اِستِدعا می‌کُنیم، از ما بِشنَو و رَحمَت نَمای.

_کر و عڤام_: خُداڤَند رَحم نَمای. (۳ بار)

_شماس_: مُجِدَداً به خاطِرِ سَراُسقُفِ مان [اِسمَش] و اُسقُفِ مان [اِسمَش] دُعا می‌کُنیم و به خاطِرِ تَمامِ مَنصوبین و عَڤامِ مَسیح نیز دُعا می‌کُنیم.

_کر و عڤام_: خُداڤَند رَحم نَمای. (۳ بار)

_شماس_: مُجِدَداً استدعا می‌کُنیم بَرایِ رَحمَت، زِندِگی، صُلح، سَلامَتی، رَستگاری، نظارت و مراقبت، بَخشِش و آمُرزِشِ گُناهانِ خادِمانِ خُدا، هَمۀِ مَسیحیانِ مُتَّقی و راست‌کیش، ساکِنان و مِهمانانِ این شَهر و سَرزَمین، اعضا، شَوراکاران، یاڤَران، و کِرفه‌گَرانِ این کِلیسایِ مُقَدَّس.

_کر و عڤام_: خُداڤَند رَحم نَمای. (۳ بار)

_شماس_: مُجِدَداً دُعا می‌کُنیم به خاطِرِ خادِمانِ خُدا: [فِهرِست اِسم‌های‌ِ مُبتَلایان] و هَمۀِ بَرادَران و خْواهَرانِ مان دَر مَسیح.

_کر و عڤام_: خُداڤَند رَحم نَمای. (۳ بار)

_کاهن_: زیرا که خُدائی رَحیم و مُحِبّ هَستی و تُرا تَجلیل می‌کُنیم: پِدَر و پِسَر و روح‌اُلقُدُّس را؛ هَمینَک و هَمیشه و تا ابَداُلآباد.

_کر_: آمین.

*** کاثیزمای بین ترانەها

مادًرِ خُدا، دَفاٛعِ مُجِّـــدانـــه، (ڤو) چِشمۀِ رَحمًت، و قَلعۀِ پاید ـــارِ ما، (ڤو) دًر اِنتِظـــار بِمـــان، ما را رَهائی ده زِ بَلاٛ ڤَ زٍ خَطًر، (ذ) اِی بانۉ تَنهاٛ فِرزٍ مَدًدِ ما. (ڤو)

*** چَهارُّمین تَرانە
**** هیرمَوس

مَن شَنؽدَمَت، خٌداڤَند، (غ)
راٛجِع به اسرـــارِ طَرح‌اٍلٰهیِ تَو، (ک)
مٌعجِزاٛتَت‌و اندؽشیده‌ٰم، (ذ)
ڤً اُلۉهیَّـــتَت‌و سٍتوده‌ٰم (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

حِیرًتِ هَڤًس‌ها را، (غ)
اٍی حامٍلِ سًر و ناخُداٛیِ ما، (ک)
ڤً امڤاٛجِ شَرارًتَم را، (ذ)
یا خُداٛعَرـــوس، آرام گَردانای. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

رَحمٰـــن را دَهر آٛڤَرده‌ٰی، (غ)
نٍجات‌بَخشِ هًر سِتاٛیِشگًرِ تَو. (ک)
زٍ ژَرفاٛیِ شَفَقًتِ خَود (ذ)
هًم بَر مَن بِبَـــخش، تَضَرٌع کُنَم. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

مُتنَعٍمِ نِعمـــاتَت، (غ)
مؽ‌خْوانؽم با شُـــکر تُـــراٛ، اِی مُنَزَه، (ک)
چًون خُداٛمادَر می‌شناٛسیمَت، (ذ)
ڤَ سِپاس گُزـــاریم زِ هِدایا. (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

ما که د ـــاریم تُراٛ به عُـــنـ(غ)ـڤاٛنِ
تٍکیه‌گــاه، ڤَ اُمؽد، و دٍژِ سِـــفـ(ک)ـتٍ
نِجات، از هَر بَلا، نِجات (ذ)
مؽ‌شَڤیم، اِی بَـــرتَرین سٍتوده. (غ)

*** پَنجُّمین تَرانە
**** هیرمَوس

ماٛ را، خُداڤًند، (ذ)
بِتاباٛن با فًرماناٛنِ خَود. (غ)
بازوی تَو بُلًند، بَر ما عَطـــاـ(ک)ـیِ
صٌلحِ تًو فَرمای، (ذ)
یاٛ عاشٍقِ آدَمی. (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

شادؽِ ناآلوـ(ذ)ـدًت‌و
بهٛ مَن بٍده اٍی خالٍص. (غ)
لَبرؽزِ شادؽ دِل‌و ساز (ک)
چًون اۉ را بٌرده‌اؽ: (ذ)
سًرچِشمۀِ هًر خَوشی. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

رَستگاٛر بُکُن ما را (ذ)
زٍ هَر خًطَرات، اِی پاٛکتَرین، (غ)
چَون تًو رَستگارؽ‌جاڤدانؽ (ک)
ڤَ صٌلحِ فًراتَـر (ذ)
زِ هًر فَهمؽ را آڤَردەٰی. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

تیرِگؽِ گُناهـــاـ(ذ)ـنَم‌و
بٍزِداٛ، خُداٛعَروس، (غ)
با تاٛبِ نافٍذِ فُرۉغِ خْویش. (ک)
مادًر شُدەٰی بِدو: (ذ)
نورِ اٍلٰهؽِ اٛزَّلـی (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

ضًعفَم را دَڤاٛ (ذ)
کٌن— ساخته زِ دًستِ هًڤَس‌ها. (غ)
به تیماٛرَت لایٍقَم بِداٛن (ک)
سَالٍمَم کُن، اِی ناب، (ذ)
دَوباره با شًفاعاٛتِ خَود. (غ)

*** شِشُّمین تَرانە
**** هیرمَوس

لابـــه‌ام راـــ (ک)
به خٌداڤَـــند مؽ‌ریزَم (ذ)
ڤً به ڤٍی دِهًم بَیـــانی زِ رَـــنجَـــم. (ن)
بِبؽن که پٌر از شُرۉر شُده دِ ـــلَـــم (ذ)
ڤَکنۉن که جاٛنَم نَزدیـــکِ دوزًخ شُدەٰست (غ)
چًون یونِـــس اٍستِدعاٛ کُنَم (ذ)
یاٛ خُداـــم از فِســـاد بَرخیزاٛن مَرا. (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

عُذرا، چَون زِ مـــرگ (ک)
ڤَ زٍ فِساٛد و تًباهؽ— (ذ)
ڤَقتؽ سِرِـــشتَم اســـیرِ فِســـاد بود — (ن)
ڤَز دَهاٛنِ مَـــوت، ذاتِ مَرا رَهـــا کَرد (ذ)
باٛ دادًنِ خَود بـــه مًحدودۀِ مَوت، (غ)
ایزًد و پۉرَت‌و بِخْواـــه (ذ)
ک‌آزاٛد شَڤَـــم از هَر کـــینِ هَر دٌشمَنا. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

می‌داـــنَم تُرا (ک)
حٍفظِ زؽستَم، و دَفـــاع، (ذ)
ڤً سِپَـــرَش، عُذراـــ؛ جًمعیّـَــتِ (ن)
ڤَسڤَسه راـــ مؽ‌زِداٛئی ڤَ حَملـــاـ(ذ)ـتِ
لَشکَـــرِ دیڤـــی راٛ دور مؽ‌رانی. (غ)
بؽ‌ڤَقفـــه اٍلتماٛس کُنَم: (ذ)
زِ فِساٛدِ هَڤَـــس بِرَهان مَرا. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

دُختَـــر، نِجـــاـ(ک)ـتِ
کامٍلِ جانِ ما، (ذ)
آرامِـــش تًوئی دَ ـــر شٍکَنجـــه ڤَ (ن)
تٍکیەگـــاه، دٍژِ ایستِ پَنـــاهی، (ذ)
ڤَز نۉرِ تَـــو تا ابَـــد ما شادی کُنیم. (غ)
اٍی بانـــو، ما را هَمینَک (ذ)
از هَڤًس و خَطَـــر رَهایؽ بِده. (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

بیمـــار، دٍرـــاز (ک)
کِشؽدَم رویِ تًختِ خَود. (ذ)
شَفاٛ بَرایِ جِـــسمَم مَوجـــود نیست. (ن)
چَون او را زــــادی: خُداٛ ڤَ ناجـــیِ (ذ)
کُلِ جَهـــان، رَهایـــی زٍ هَر بؽمارؽ، (غ)
اٍی نیکـــو، مًرا بٍشنَڤـــا: (ذ)
زِ پوسٍشِ مَرَـــض بًرخیزاٛن مَرا. (غ)

*** دُڤُّمین ترَوپارِ اتمام

اِی بیـــگُنــــاه (ک)
که با لُغًتی کَلــــامِ جاڤیدو بُـــردی (ذ)
بی‌بَیاٛن اِلتِماٛس کُن هَمینَـــک و دَر ا‌ِنتِها (ن)
به اٍختیّاٛرِ مِـــهرِ مادَ ـــری. (غ)

—(در این موقع، دعای گستردۀ سوزان دوباره اجرا شڤد)—

*** کوداکیون عادی

حِفاظًتِ ناشًرماندَنؽِ مَسیـــحیّـــان (ذ)
میّانجؽ به خالٍقِ اصلاً ناجُنبیـــدَنـــی، (ڤو)
ناله‌هـــایِـــ مایِ عاصؽ را مَیاَنداٛز کِنـــار؛ (ذ)
بِجـــا، بٍنِگَر حاجاٛتِ مان، ڤَ دٍه کُمًکِ مان، اِی نیـــک، بًر نِداٛگَران دَـــر ایمان: (ڤو)
زـــود باش به شَفاعًت، وـــ بـــه اٍستِدعا شِتاٛبـــی. (ذ)
دائِماً پاسباٛنِ هَـــر (ظ) تَکریم‌گًرَت اِی خٌـدازا.ـــ (ڤو)

*** TODO مزامیر صعودی
*** قرائت انجیل
**** پیش‌نشین
:PROPERTIES:
:بین الکلیسائی: ترجمه
:END:

_قاری_: می‌خْواهَم نامِ تَو را دَوره به دَوره به یادها آڤَرَم.

—(اڤلین کر همان آیه را به لحن تکرار کنه. بعد، قاری این آیه را بخْواند و دڤمین کر آیۀ اصیل را به لحن تکرار کند.)—

آ. اِی دُختَر، گوش فَرا دِه، بِبین و گوش بِسپار، قَومِ خَود را فَراموش کُن، خانۀِ پِدَرَت را، و پادِشاه شیفتۀِ زیبائیِ تَو خْواهَد شُد.

—(یک بار دیگر خْوانده شڤد. این دفعه، اڤلین کر اڤلین نصف آیه را بخْواند و دڤمین کر جڤاب دهد با بقیه.)—

_کر یکم_: می‌خْواهَم نامِ تَو را دَوره
_کر دڤم_: به دَوره به یادها آڤَرَم.

**** انجیل

_شماس:_ به خُداڤَند دُعا کُنیم که ما را لایِق سازَد تا اِنجیلِ مُقَدَّس را بِشنَڤیم.

_کر و عڤام_: خُداڤَند، رَحم نَمای. (۳ بار)

_کشماس_: خِرَد. بُلَند شَڤید! اِنجیلِ مُقَدَّس را شَنَڤیم.
_کاهن_: صُلح بَر هَمۀِ شُما باد.
_کر و عڤام_: نیز بَر روحِ تو.

_شماس_: خانِش از اِنجیل است مُطابِقِ شَهادَتِ لوقایِ رَسولِ مُقَدَّس.
_کاهن_: تَڤَجُه گُزاریم.
_کر و عڤام_: جَلال بَر تَو، اِی پَرڤَردِگار؛ جَلال بَر تَو.

—(در این موقع، کاهن یا شماس انجیل را بخواند از کتاب لوقا، باب اڤل، آیه‌های ۳۹–۴۹ و ۵۶.)—

_کر و عڤام_: جَلال بَر تَو، اِی پَرڤَردِگار، جَلال بَر تَو.

*** سرودگانِ بعد از ا‌ِنجیل

/جلال بر پدر و پسر و روح‌اقدس؛/

پِدًر، پِسًر، و رـــوح، ثالَُــوث د‌َر یِکپارچِگی، (ڤو) رَبِ رَحمًت، خَطـــایٍ زیاٛدَم‌و پـــاک کُن. (ڤو)

/همینک و همیشه و تا ابد الآباد. آمین./

به خاطٍرِ شًفـــاعاٛتٍ ثِـــئَوتًوکوس، (ڤو) رَبِ رَحمًت، خَطـــایٍ زیاٛدَم‌و پـــاک کُن. (ڤو)

/(آیه) ای خدا، مطابق وفاداری‌ات بر من رحم فرما، مطابق فراوانی شفقت خود خطایم را بزدا./

(به لحن ὅλην ἀποθέмενοι)
بانۉ نَسٍپارؽ مَرا به پَناهگاٛهی انساٛنـــی (ذ)
بَلکه بٍپَذؽر لابـــۀٍ خادٍمی فٌروتَـــن، اِی بانوی‌اقدَس. (ڤو)
مُشکِلـــات دًورَم گٍرِفتًند؛ دیگًر نَتًڤانًم (ذ)
تیرهایِ شٍیطانان‌و تًحَمُـــل بٌکُنَم از هًر سو تَــــحتٍ آتًش، ناچـــار و خًراب چُنین. (ڤو)
پًناهگاٛهی نًدارَـــم ڤً هیچ تًسلیَّـــت جٌز تَو نیز، تَو اِی (ڤو)
مًلَکًۀِ دَ ــــهر ۉ اُمؽد و حِمایًتِ پای‌بَنداٛن، (ذ)
به اِلتِمـــاسَم دِقًّت دِه، و (ذ)
انجاٛم ده آن که بِـــهیـــنــــه‌ست (ڤو)

هیچ‌کًس رَد نًکُن شًرمَنده، خَلڤًت، و بؽ‌فایِده که می‌دَڤَند پَناٛهَت، اِـــی باٛکِره خُد ـــازـــا، (ڤو)
بَلکه اِلتِماٛس کُنًد و هَدیّهٰ‌ت‌و می‌گیرًد (ذ)
به انجـــامٍ دَرخْواـــستِ‌ـــ خْویـــش. (ڤو)

دِگرسازؽ بَهرؽ رنجبَـــران (غ)
ڤَ تَسکین بَهرؽ بیمـــاران ڤاقعاً هَستی، اِی باٛکِره خُد ـــازا (ن)
شًهر و قًومَت‌و نِجـــات (ذ)
دِه، اِی صٌلحِ دًر مُحاٛصِره‌ها (ذ)
آرامٍش بَهرِ دًرگیراٛنِ طوفـــان نیز (ڤو)
ڤَ تَنها حافِظٍ ایمان‌داران (ذ)

*** شفاعت کبیر

_شماس_: ای خدا، قوم خود را نجات فرمای و میراث خود را برکت نمای. بر دنیای خود با رحمت و شفقت بنگر. مسیحیان راست‌کیش را در جلال براَفرازان و رحمت‌های فراڤان و انبارۀ ترا به‌افشان بر ما، از طریق شفاعات بانوی پاکیزۀ مطلق مان: تئوتوکوس، مریم دائماً باکره، با قدرت صلیب حیات‌بخش و گرانبها، پاسبانیِ قدرت‌های بزرگڤار ناجسمی آسمانی، با استدعاهای پیش‌رو و نبی بزرگڤار مجلل: یحیای تعمید دهنده، همراه همۀ رسولان مجلل و قابل ستایش، پدران مان در میان قدیسان و کاهن‌سرڤران و اموزگاران کیهانی: ڤاسیل کبیر، و سرمطرانان قسطنطنیه: گریگوری عالم الهیات، و یوحنای طلادهن؛ سرمطرانان اسکندریه: آثاناسیوس، کیریل، و یوحنای رحیم؛ شگفت‌سازان: نیکولائوس اسقف شهر میرا، اسپِرِیدونِ اسقف شهر ترمیثوس، و نکتاریوس اسقف شهر پنطوپولیس؛ شهیدان: گِوارگئوس پیروز، دمیتری مُرّتَراڤ، ثئودور نوسرباز،  ثئودور فرمانده، و میناس شگفت‌ساز؛ کاهنان شهید: حرالابوس و الفثریوس؛ اِفّیمیای شهیدِ پر شکوه و فراشایستۀ تمجید، و بقیۀ شهیدزنان مقدس و مجلل: ثکلا، ڤارڤارا، آناستاسیا، اکاترینا، کریاکی، فْواتینی، مارینا، پاراسکڤی، و ایرینی، و جمع شهیدان مقدس مجلل پیروز، و جمع پدران خدابر مان؛ نیاکان ایزدی دادگر: یوئاقیم و آنّا، و قدیس [اسمش] که امروز خاطرۀ او را جشن می‌گیریم، و همۀ مقدسان تو. ترا التماس می‌کنیم ای خداڤند یگانۀ رحیم، که مای گناه‌کاران را بشنڤی که به تو دعا کنیم و که بر ما رحمت فرمائی.

_کر و عڤام_: خُداڤَند، رَحم نَمای. (۱۲ بار)

_کاهن_: از رحمت و شفقت و محبت برای انسانیت پسر یگانۀ تو که با او و با روح قدوس مطلق و نیک و حیات‌بخش متبارکی، همینک و همیشه و تا ابدالآباد.

_کر و عڤام_: آمین.

*** هَفتُّمین تَرانە
**** هیرمَوس

سه جَڤاٛنِ یَهۉدیّه، (غ)
به ایماٛن به ثالًوث قُدوـــس رٍسیده، (غ)
باٛری دَر باٛبِـــل (ذ)
شُعلەهاٛیِ کورـــه را پایماٛل کُنان سٌرودَند: (غ)
اٍی خُداٛیِ پِدَراٛنِ مـــا، یًهُڤًه مُتٍبارِـــکی! (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

مُشتاقِ رَستگارؽ‌مون، (غ)
اٍی ناجؽ، نِجـــاتِ ماها را نٍهادی (غ)
دَر زِهداٛنِ باکِرهٛ، چَون (ذ)
حافٍظِ جَهـــان نَمودەٰـــیٰ‌ش، تَو ساکٍنِ دَهر. (غ)
اٍی خُداٛیِ پِدَراٛنِ مـــا، یًهُڤًه مُتٍبارِـــکی! (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

از پِسًرِ تَو بٍخْواه، (غ)
کامجۉ، اِی مادَ ـــر، که رَحمًت دِهًد به ما، (غ)
تا از عِیب آزاٛد شَڤـــیم (ذ)
ڤَز نٍجاسًتِ رـــوح، که نِداـــ زَنیم باٛ ایمان: (غ)
اٍی خُداٛیِ پِدَراٛنِ مـــا، یًهُڤًه مُتٍبارِـــکی! (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

زایَندەٰت‌و نَمودی: (غ)
بٌرج‌ِ ایمِنـــی، ڤَ چِشمۀِ لافِساد، (غ)
گَنجینۀِٛ نِجاٛت، وـــ (ذ)
دَرڤازۀِ تَوبه بَراٛیِ هًمه که سٍتایَند: (غ)
اٍی خُداٛیِ پِدَراٛنِ مـــا، یًهُڤًه مُتٍبارِـــکی! (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

ناخَوشؽِ بَدًن وـــ (غ)
بیمارؽِ جـــان را، اِی تًو خُداٛمادًر، (غ)
شَفاٛ ده بًهرِ ماهـــا (ذ)
عُشاٛق که آییـــم به پَنـــاه اِلٰهؽِ تَو. (غ)
براٛیِ ما، مَســـیح و ناجــــی را زادەـــ‌ای. (غ)

*** هَشتُّمین تَرانە
**** هیرمَوس

پادِشـــاهِـــ (ک)
آسِماٛن را بٍسُرای، (ذ)
با سٍپاهـــانِ سِپٍهرِ بی‌شُمـــار، ڤَـــ (ن)
بؽکران دَر هَـــر زَمانه او را ڤالـــا کُن. (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

بانو، نَدیـــده مَگـــیر (ک)
خادِماٛنِ گِداٛت‌و (ذ)
که با شَرَـــف و شاد ـــی می‌سُرـــایَند (ن)
ڤَ تٌرا، اِی دُختَـــر، هًر دَوراٛنی می‌سِتـــایَند. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

می‌‌بَـــخشی (ک)
شَفاهایِ فًراڤان، (ذ)
اِی باکرهٛ، بَراٛیِ هَـــر خْواٛنَندەٰـــت کـــه (ن)
زادًنَت‌و سِتـــایَند که فًرا زٍ گُفتـــاره. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

اِی لَبریـــزِ فِیض (ک)
هَر مَرًض و ضًعفِ جان (ذ)
ڤَ رًنجِ تَـــن را شَفـــا می‌بارـــانی، (ن)
تا سٍتایِشِ فَـــرِّ تُراٛ نِگًه بِد ـــارَم. (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

تاختِ هَڤَـــس‌ها ڤَ (ک)
حَمَلاٛتِ اِغڤـــا را (ذ)
عُذرا، خُنثٰـــی ڤَ زِ مـــا دور می‌رـــانی، (ن)
ایدۉن تا هَر دَورـــه سِتایٍشگَرانِ تَـــو ایم. (غ)

*** نُهُّمین تَرانە
**** هیرمَوس

نِجـــات‌یاب از طَرؽقَت، (غ)
اِی باکِره، اقرـــارَت (ک)
کُنیم که دًر حَقیقَـــت تِئَوتًوکوسی (غ)
با جًمعِ کٌرِ افلـــاک، مـــا بُزٌرگَت مؽ‌داریم. (غ)

**** ترَوپاریا

/ای تئوتوکوس‌اقدس، ما را نجات ده/

رَدّ نَـــکُن رۉدِ اًشکَم (غ)
چًون تَو دَر زِهد ـــانَت (ک)
او را بُردەٰـــی که هَر اـــشکِ هَر قؽافه (غ)
را زُدودهٛ چون مَســـیح است: ایزًد آدًم‌زاده. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

اِی بـــاکِره دِلًم‌و (غ)
پٌر کُن از مُژد ـــه، چَون (ک)
شادؽِ هًمه دَریـــافت کًردی تۉ زِهداٛن، (غ)
ڤَ هًر اندۉهِ گُنـــاه رـــا تَو بٌردەاؽ زِ بِین. (غ)

/ای تئوتوکوس‌اقدس، ما را نجات ده/

عُذرـــا، بَندًر و پًنـــاه (غ)
ڤَ دٍژِ سِفت بَرـــایِ (ک)
اونا باش کهٛ به سایـــەات فَرار کُنًند، (غ)
ڤَ حِفاظًت احاطـــەٰشـــون شَڤؽ خُداٛمادَر. (غ)

/جلال بر پدر و پسر و روح‌القدس؛/

پَرتَـــوهایٍ فُرۉغَت (غ)
دٍه، اِی دوشیزـــه، تـــا (ک)
ما را رَوشًن از ظُلمَـــتِ غِفلًت کُنی (غ)
که پارسانه اِعِلام کُنـــیم تُراٛ، یَاخٌدازا. (غ)

/همینک و همیشه و تا ابدالآباد. آمین./

دَر مَـــنطِقۀِ بًلا، (غ)
نِزاٛر، زِ کار اُفتـــادَم، (ک)
ڤَ شُدم خْواـــر، یَاعُذرـــا، بِدونٍ قُڤًّت؛ (غ)
مَرًضِ مًرا دَڤـــا ڤَـــ تَبدؽل کُن به قُدرًت. (غ)

**** عظیم‌نماها
***** عادیِ تضرعات

/فًرخُنده گُفتًنَت شایِستـــهٰ‌ست (ذ) بهٛ راستؽ، ڤالٍدۀِ خٌداـــمون، (ذ) داٛئِماً سَعؽد، هَمیشه مٌبارَـــک، تِئَوتًوکوس، جُمله بؽ‌گُناه. (غ)/

اًز کِروبیّـــان شًریف‌تًر توئؽ (غ)
ڤًز سِرافیــــان تَـــو بی‌نَظـــیر باٛشُکۉه‌تَرؽ (غ)
کَلَمَت‌اُللّٰه‌ راــــ زادؽ بِدۉنِ فٍســـاد؛ (غ)
ڤاقعاً توئؽ خُداـــزاـــ؛ بُـــزٌرگَت مؽ‌داریم. (غ)

باٛلا زٍ افلـــاک توئی، ڤَ پاک‌تًر (غ)
از نورِ آفتـــاٛب، اِـــی تًو بانـــویِ کُلٍ جَهان، (غ)
ماٛ را رًهاندؽ زــِـ نِفرؽنِ نیّاکاٛنـــی (غ)
پَس سٌرایاٛن تَجلیـــلَـــت گُـــزاریم باٛ شَرَـــف. (غ)

آه زیراٛ انبـــوهِ گُناهِ مَن (غ)
جٍسمِ مَن مَریـــض است، رۉحَم نیـــز هًمچُنین بیماٛر (غ)
دًر لابه خْواندًنَـــت، مَن مؽ‌دَڤَم پَناٛهَـــت، (غ)
اِی تًو لَبرؽزِ فِیـــض و اُمیـــدِ بی‌چاٛرِگـــان. (غ)

اًز خادٍمی نَـــشایِسته قَبـــول (غ)
بٌکُن لابه‌هـــا را به شًفاعَـــت به خاطٍرِ ما (غ)
باٛ او که آڤًرد ـــی، اِی ڤاٛلِدۀِ مٌنجـــی (غ)
بَراٛمون شَو شفـــیعِ، اٍی بانـــویِ جُملهٛ‌ جَهان. (غ)

ماٛ این تَرانـــه را مُشتاٛقانه (غ)
شاٛد به تَو، خُداـــزاـــ، میٛ‌سُراـــئیم. ایدۉن با هَم (غ)
باٛ یَحیاٛیِ پؽش‌رَوـــ ڤَ جًمعِ مُقَدًّساـــن (غ)
دُعاٛ کُن، تِئَوتَـــوکـــوس، بر مـــا شَفَقًت آیًد. (غ)

لاٛل شُده لب‌هـــایٍ بی تًقڤایاٛن (غ)
کهٛ حُرمًت‌و رَـــد کَـــرد به نِگـــارِ ڤالایِ تان (غ)
کهٛ مَوسۉم به نٍشان‌دٍهِ حًقیقین راٛه است (غ)
تًڤَسُطِ لـــوقا قِدیـــس و اِنجؽل‌نِڤؽس. (غ)

***** TODO اضافه برای عیاد

—(در این موقع سرودگان بزرگنمای دیگر خْوانده شڤند: برای عید معبد محلی و اگر روز کنونی یه جشن کبیر باشد، بزرگنمای آن نیز خْوانده شڤد)—

***** آخرین عادیِ تضرعات

شٌما سٍپاهـــانِ آسٍمانؽ، (غ)
پؽشر‌َڤٍ ڤالـــایِ‌ـــ، رًب و رَسولان دَڤازدَه‌ـــ، (غ)
ڤً جمله قدؽســـان، بٍپِڤًند با ثئوتۉکوس: (غ)
دُعاٛ ڤَو شَفاعَـــت ده بَراــــیِ نِجاٛتِ ما.(غ)

*** دعای سه‌قدوس

—(دعای سه‌قدوس دوباره برخْوانده شڤد.)—

*** اپولیتیکیای پشیمانی

رَحمَت ده به ما اِی خُداڤَند، رَحمَت ده به ما، زیرا از هَرگونۀ دَفاٛعی ما عاجِریم. مایِ گُناه‌کاران این اِلتِماس را به دَستِ تَو می‌آڤَریم اِی سَرڤَرِ مان رَحمَت ده به ما.

/جلال بر پدر و پسر و روح‌القدس؛/

اِی خُداڤَند رَحمَت دِه به ما چَون هَر اِعتِماد را سِپُرده‌ایم به تَو. بَر ما کُلِ خَشمِ خَود را نَریزان و به یاد نَسِپار، بَلکه الان هَمچَون رَحمٰن به ما بِنِگَر و ما را از دُشمَنانِ مان بِرَهان، چَون خُدایِ مانی و قَومِ تُوئیم؛ هَمۀِ ما کارِ دَستِ خَودَتیم و حالا بَر اِسمِ تَو نِدا زَده‌ایم.

/همینک و همیشه و تا ابدالآباد. آمین./

دَرڤازه‌هایِ شَفَقَت را بُگشای به ما اِی اقدَس و خُدازا، با هَر اُمیدِ مان سِپُرده به تَو، ناکام نَمانیم. از طَریقِ تَو بِرَهیم از هَر بَلا، چَون رَستگاری هَستی بَر نِژادِ مَسیحی.

*** گستردۀ سوزان افزوده

—(مجدداً گستردۀ سوزان برخْوانده شڤد ولی این دفعه، تضرعات اضافه هم برخْوانده شڤند بعد از خْواندن فهرست نام‌ها و پیش از مهر کاهن:)—

_شماس_: موجددا دعا می‌کنیم برای حفاظت این کلیسای مقدس و این شهر و هر شهر و هر ده، و رهانیدن شان از مرض، طاعون، گرسنگی، ڤز هر زلزله، سیل، آتش، شمشیر، ڤز یورش دشمنان، جنگ داخلی، ڤز گشتگی غیر منتظره. و برای رحمت او، که بخشنده و مهربان باشد که چو خدای نیک مان دقت دهد به ما، که محب همۀ افراد هست، ڤ برای این که هر خشم و مرض را از ما به‌افشاند و دور براند که برعکس ما کار می‌کند، و ما را نجات دهد از داڤری آیندۀ دادڤر خود که زود می‌آید، و رحمت دهد به ما.

_کر و عڤام_: خداڤند رحم نمای. (۳ بار)

_شماس_: مجدداً دعا می‌کنیم که خدای خداڤند صداهای لابه‌های مای گناهکاران را بشنڤد و رحم فرماید بر ما.

_کر و عڤام_: خداڤند رحم نمای. (۳ بار)

_شماس_: ما را بشنڤای، یاخدای ناجیِ مان، امیدِ هر دڤائرِ زمین و برای آنانی که دور بر دریا هستند، و شفقت نمای بر ما، ای استاد ما، و نیز بر گناهان فراڤان مان، و رحمت فرمای بر ما.

_کر و عڤام_: خداڤند، رحم نمای. (۳ بار)

_کاهن_: زیرا که تو یه خدای رحیم هستی، و ترا تجلیل می‌کنیم، پدر و پسر و روح‌القدس را، همینک و همیشه و تا ابدالآباد.

_کر و عڤام_: آمین.

*** برکت مرخصی

_کاهن_: مسیح، خدای ڤاقعی مان با شفاعات مادر پاک مطلق و جمله بیگناه خویش، ڤز قدرت صلیب عزیز و حیاط‌بخش، حفاظت قدرت‌های بی‌جسم گرامی آسمانی، التماس‌های نبیِ شریف و باشکوه یحیای پیش‌رو تعمیددهنده، و رسولان مقدس  و مجلل و ستودنی، شهیدان پیروز، و پدران عادلِ خدابر، نیایان گرامی مسیح، یؤاخیم و حنا، و همۀ مقدسان، رحمت فرماید بر ما و نجات دهد، چون نیکو و عاشق آدمیت هست.

*** ثئوتوکیای مرخصی و نیایش

(به لحن Ὅτε ἐκ τꙋ͂ ξύλꙋ)

دَ ـــستَـــت نیرومًند، تَو حٍفاظًت (پا)
بًر پَناه‌دَڤاٛنِ مَؤمِـــنَـــت می‌بَـــخشی، نیکۉ. (غ)
ماٛیِ عاٛصیّان شَفؽعی جٌزِ تَـــو نًداریم (پا)
کهٛ دُعـــا بی‌ڤَقفهٛ کُنَـــی (ن)
به حُضۉرِ خُداٛ بَـــراٛمون تًقصیراٛت‌بَران دَر هًر مَرَـــض و خَطَـــر. (پا)
پَـــس مـــی‌خًمیم فٌروتَن پؽشَـــت (غ)
اٍی مادًرِ بًغِ بَریـــن گـــاه (ذ)
خاٛدِم‌هاٛت‌و بٍرَهاٛن از فًلاکـــات. (پا)

بـــه اَـــندۉهگیناٛن تَوئؽ شادی (پا)
ڤً به مَظلوماٛن حِفاظَـــت، بـــه گُرٌسنِگاٛن غَذا، (غ)
بهٛ کوراٛن عَصاٛ، به غًریبـــان تًسلیًّت (پا)
عٍیادَ ـــت بًهرِ مًساکیـــن (ن)
ڤَ به مٌبتَلایاٛن، آـــشتؽ و ساٛیِباٛنی، ڤً به یَتیمـــان یاڤَری. (پا)
مـــادَ ـــرٍ خُداٛیِ بَرؽن گاه، (غ)
بٍشِتاب اِی پاٛک، به لابـــه‌مون: (ذ)
بٍرَهاٛن خِدمًت‌کاراٛنَت از گُناه (پا)

—(بعد، دو ثئوتوکیای دیگر. اڤلش در قصمت مخالف چهارمین آڤاز در هشتآڤازنامه پیداست ڤلی رسمی است که در این موقع هردو بنظر دڤمین آڤاز خْوانده شڤند.)—

بِـــپَذیر اٍی بانـــو دُعاهـــا زٍ خُدّاٛمَت و (پا)
رَهاٛ بُکٌن ما را (ذ) از نیّاٛز، تَشڤؽش، و هًر اندوه. (پا)

سپُـــردَم به پؽشِ تَـــو هًر اُمیـــدَم، خُداٛمادَر. (پا)
لُطفاً مَرا نِگـــه‌داـــ(ذ)ـرؽ در بندرگاٛهِ تَو. (پا)

*** پایان

_کاهن_: با شَفاعاتِ پِدَران و مادَرانِ مُقَدَّسِ مان، اِی خُداڤَند یَسوعِ مَسیح، بَر ما رَحمَت و نِجات فَرما.

_کر و عڤام_: آمین.

*** Attributions

Everything in this document, unless noted otherwise, was translated by me, Anastazius, Khayatidaryan.

The verses at یهڤه خداست we're taken directly from the ecumenical translation of the holy scriptures «ترجمۀ بین الکلیسائی» also known as «ترجمۀ ترسایان».

The verse before each of the troparia of the canon was suggested by our brother Petros (Kyan). Prior to his suggestion, what I had was «قدسی‌ترین تئوتوکوس، ما را نجات بده.»

Early on in the process, there was an anonymous user in telegram who gave me a lot of feedback on odes I and III. Unfortunately, I cannot identify this person, and he has deleted his account, and later, I lost access to my account.

*** A Note About the Tetragramaton

You'll notice that in various places we translated what in Greek is «Κύριος» ( “Lord”) into Persian as the tetragramaton itself, rather than the equivalent, خداڤند or similar. This is to align with the aforementioned ecumenical translation which favours the use of the tetragrammaton over its euphemism. This may be seen as a questionable choice as the Septuagint favors the euphemism over the actual tetragrammaton, and therefore some may decry it as an unorthodox decision. From my perspective, the ecumenical translation is the closest thing that we have to an Orthodox translation of the scriptures in the Persian language, so I would rather align with it than to not do so. For anyone who disagrees, the word can be substituted easily with خداڤند as needed, as they are both trisyllabic.

*** A Note About Orthography

You will also notice that my spelling of certain words is a little bit non-standard. For example, I used the archaic Persian letter, veh ڤ, as a substitute for waw و in some places. This is because we have a great need for precision in the translation of metrical texts. And the current Persian orthography harkens back to a time when rather than a solid V sound, the Persian language was pronounced with a bilabial fricative. Now, the phonetics have diverged, and in the modern orthography, the one و letter is overloaded with at least four different pronunciations:
- دو (ō)
- دعوا (v)
- لوله (ū)
- خواهش (silent or w)

And sometimes, the same word with the same spelling can be pronounced in multiple ways with different syllabic contents. This is fine, but within this domain we have a greater need for precision, so we've brought back the old persian letter ڤ so that و is slightly less overloaded.

Now, ـَو can unambiguously make the ō phoneme, and ـو/ـُو can unambiguously make the ū phoneme, while ـْو can make the silent phoneme.

Without this ـَو might have been “av,” ـُو might have been “ov,” etc. and there is no standard diacritical method to distinguish between these sounds. With the return of this old letter, however, the diacritics become sufficient to describe the phonemes with adequate specificity.

Next, you will notice sometimes we doubled the diacritics or used the nasalized forms of the diacritics. This can be thought of generally as an indication of accentuation. However, within metrical hymnography, its purpose is more precisely to indicate downbeats and melodic high points.

You will also notice that certain syllables are elongated with the کــــــــــــشیده symbol. This can generally be thought of as an indication of elongated phonemic vowel length. However, more precisely in the context of metrical hymnography, it is being used to indicate when a syllable is held for longer than one beat.

